/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarouselComponent: typeof import('./components/projectsPreview/Carousel/CarouselComponent.vue')['default']
    MenuItems: typeof import('./components/layouts/MenuItems.vue')['default']
    MobileCardsComponent: typeof import('./components/projectsPreview/MobileCards/MobileCardsComponent.vue')['default']
    Profile: typeof import('./components/account/Profile.vue')['default']
    ProjectsPreview: typeof import('./components/projectsPreview/ProjectsPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
