/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InitialPage: typeof import('./components/InitialPage.vue')['default']
    MenuItems: typeof import('./components/layouts/MenuItems.vue')['default']
    ProjectsPreview: typeof import('./components/projectsPreview/ProjectsPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
